### ISSUE TITLE
IMPORTANT: Not an issue with your code, but please read

### ISSUE THREAD

**Issue by sean-niemann** [OrN/rscplus#107]
I see you're still actively developing this project (which you've done a fantastic job at so far). But, if you for some reason have not heard, RuneScape Classic is closing permanently (http://services.runescape.com/m=news/runescape-classic-farewell?oldschool=1#_ga=2.4429179.991386156.1527740804-1592310312.1525070064). I feel like you deserve to know if you don't already. If you need to get back to me, just repond here, or you can email me at sniemann@cs.arizona.edu.

PS: Sorry if this is old news, but it wouldn't make sense why you'd still be committing to the repo if you knew.

**Comment by Hubcapp** [comment]
Thanks for your concern, Sean!

We've been aware the rs1 servers are closing since about an hour after the announcement, and it's actually what has motivated the latest changes. We added software preservation related features to RSC+ to capture data coming from the server, and allow in-client playback of recorded sessions for when the servers do go offline in 66 days.

I've noticed some new minor features aren't preservation related, and that does seem a little funny to me, but working on RSC+ has always been a "for fun" activity, and I guess that hasn't changed. A lot of people are logged in right now trying to finish up goals that they thought they'd have a lot longer to complete.

**Comment by OrN** [comment]
@Hubcapp looks like we have a reason to continue working on the client then!

**Comment by sean-niemann** [comment]
@Hubcapp @OrN - That's actually a quite interesting and brilliant idea, in regards to capturing recorded sessions. But what if I told you this:

I've been developing a completely functional single player version of RS Classic since 2015, which I plan to release on the day that the original RS Classic hosted by Jagex is taken down.

Check out my old post (when it was beta development) and tell me what you think, however keep in mind that's a VERY old build. The current build (which has already been beta tested by about 5 individuals of the community) includes literally every quest (up to and including legends), and every piece of content RSC had to offer (no not 99% of the content; every fucking thing). Think of it as a lightweight 1 player RSC that will go nowhere, due to the fact that there is no server, and the game ("client") handles itself entirely. If I were to say this has been "one hell of a task", that would be an utter understatement. No words could describe would me and some other devs went through to create this.

The old build is located here (just keep in mind, its come a very long way since this 2015 build): https://forum.moparscape.org/rsc-server-development-discussion/52/beta-rsc-single-player/672287/

Three years later, and we have managed to recreate RSC and all its pixelated glory, in its true entirety. All the quests that were not completely finished, were used from the current server build of RSCR (May 3rd) (yes I have the build), including everything other aspect of the game. No fancy additions (although I loved what you did!), just good old vanilla RSC, soon going open source and will be free to the public. I've had a handful of people over the last year beta test the current build of my project, and it finally looks like it may be finally ready for distribution (if that's what I decide on doing - read on).

So my question to you (I want to get your opinion as well): Would this be something that the community would love to see? And if so, do you think it should be open source (I'd probably give you the source privately) or closed sourced?

Cheers.

**Comment by sean-niemann** [comment]
Also, I've been tinkering with porting the build to Objective-C (https://forum.moparscape.org/rsc-server-development-discussion/52/ios-rsc-objective-c-port-almost-completed/681913/)
