### ISSUE TITLE
Fatigue bar doesn't update while you're sleeping

### ISSUE THREAD

**Issue by ShaunDreclin** [OrN/rscplus#110]
Not sure if this would be a pain to fix or not, but the fatigue overlay doesn't tick down while you're sleeping, it just updates once after you wake up.

**Comment by Hubcapp** [comment]
That's the real behavior. If you don't put in the correct word before a monster attacks you or you log out, your fatigue doesn't get altered.

**Comment by ShaunDreclin** [comment]
Oh interesting :o so the counting down number is just to give you an idea of when you can wake up?

**Comment by lmsv-mx123** [comment]
Yea it just an idea like for instance if you had 100% and when you finished typing the word is at 40% and you press enter, the new fatigue would be 40%. Stalling time after 0% is just wasting time. Also that overlay is the one that was original from the game

**Comment by ShaunDreclin** [comment]
Ahh yea makes sense
