### ISSUE TITLE
Add world populations on world select screen

### ISSUE THREAD

**Issue by Taltin** [OrN/rscplus#2]
I haven't seen anyone else leave any suggestions. Do you prefer suggestions to be submitted here or somewhere else?

**Comment by OrN** [comment]
It's fine to post it here, I was thinking about adding world population to the login screen + for worlds, if you want to add it yourself feel free to and open a pull request. I'm a bit busy atm.

**Comment by TzZek** [comment]
Could you possibly show us how to properly jar it up i've just been tinkering with some things but can't seem to get it jar'd right.. :(

**Comment by OrN** [comment]
I just use ant for final builds that are shared, didn't really mess with the eclipse setup other than get it running.

**Comment by TzZek** [comment]
Oh hmm i'm not sure how to do that either xD

**Comment by TzZek** [comment]
Nvm was able to follow a few things to do it

**Comment by OrN** [comment]
This is fixed by https://github.com/OrN/rscplus/pull/6
