### ISSUE TITLE
Finnish keyboard layout doesn't allow shift key

### ISSUE THREAD

**Issue by OrN** [OrN/rscplus#22]
I saw this on https://www.reddit.com/r/rsc and figured I would put it here.

> Teditys: Im eager to try out the RSC+ client instead of the basic client, but Im not able to type my login "username" because its an email address and contains "@". If i press "command" + "2" client instead attempts to jump wolrd. ([Command Key] + 1-5 - World switch on login screen). Anyone ideas to solve this?

> Teditys: Ah ok i got it now, changed my keyboard to "English" from "Finnish" to be able to make @ with shift+2. Thanks!

No idea what the shift key is being recognized as in that case, it may be a good idea to make the command key changeable.

Original Link: https://www.reddit.com/r/rsc/comments/4x4a6w/rsc_log_in_technical_issue/

**Comment by thelegendofbrian** [comment]
I'm already working on making changeable keybinds for things, I'll add that to the list. Might just want to make a temporary workaround for now? My pull request will probably take until next week to submit.
![ui](https://cloud.githubusercontent.com/assets/2666891/17787739/353b911c-653f-11e6-8dfe-28ed6d5ede26.gif)

**Comment by OrN** [comment]
Looks great!

I'm not exactly sure what we could do for a workaround yet, would need more info on the bug... the workaround for now appears to just be set the keyboard layout to English, as bad as it sounds.

**Comment by OrN** [comment]
This probably isn't an issue anymore now that PR https://github.com/OrN/rscplus/pull/24 is merged.
