### ISSUE TITLE
Client fails to load

### ISSUE THREAD

**Issue by thelegendofbrian** [OrN/rscplus#29]
Not sure if there was an update on Jagex's side or what, but the RSC+ client no longer loads. Issue occurred on Windows 10. It hangs here:
```
[ INFO] Retrieved file: bc.class
[ INFO] Retrieved file: na.class
[ INFO] Retrieved file: sb.class
[ INFO] Retrieved file: s.class
[ INFO] Loading resource: /assets/icon.png
[ INFO] Found logout
java.lang.NoSuchFieldException: C
        at java.lang.Class.getDeclaredField(Unknown Source)
        at Game.Reflection.Load(Unknown Source)
        at Game.Game.start(Unknown Source)
        at Client.Launcher.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[ INFO] Loading resource as stream: /assets/Helvetica-Bold.ttf
Started applet
[ INFO] Loading resource as stream: /assets/TimesRoman.ttf
[ INFO] Loading resource: /assets/border.png
[ INFO] Loading resource: /assets/bar.png
[ INFO] Loading resource: /assets/cursor.png
Error: i.B({...},null,-118) vb.T(0,null) vb.O(true) | i.a vb.a vb.a vb.run java.lang.Thread.run | java.lang.NullPointerException
error_game_crash
```

The official RSC client works fine though.

```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by Hubcapp** [comment]
Yep, can confirm...

**Comment by Hubcapp** [comment]
On the positive side, once @OrN updates the client (plz) everyone who uses RSC+ will update to the latest version, since all previous versions are broken. Might be a good time to accept Brian's pull request.

I also thought a "new version available" feature would be a good idea. I think all you need to do is put a text file with current version number in it in the repository somewhere and have the client read their local copy of that file compared against the version at https://github.com/OrN/rscplus/CurrentVersion.txt

**Comment by OrN** [comment]
They updated the RSC client? R.I.P.

**Comment by OrN** [comment]
I grabbed a cache dump off of a friend and rebuilt the rsc jar they used in the previous version, unfortunately this happens: http://i.imgur.com/BDUWRXv.png

I'll see if I can disable the version check and hope for the best. This would be a temporary fix, of course, until somebody can get around to updating the class patcher and reflection... but it may not work.

**Comment by OrN** [comment]
Alright, this is fixed by https://github.com/OrN/rscplus/commit/29409480fa5b8e2a9769b3dac7bd421302325200 but it's a hack.

We can skip updating the client this time, I had to mirror the old rsc jar though until we have a proper fix.

**Comment by thelegendofbrian** [comment]
For those interested, this is what the update was about:
![image](https://cloud.githubusercontent.com/assets/2666891/19413315/68403da2-92de-11e6-8834-ab77bda883ae.png)
