### ISSUE TITLE
Resizing 

### ISSUE THREAD

**Issue by TzZek** [OrN/rscplus#3]
Was trying to make it so once expanded it could be shrunk back down again but I can't seem to get it to work, and when i ended up making it into a jar, if i would enlarge it to much it would go to a black screen or not allow me to log in.

**Comment by OrN** [comment]
Is this fixed in the latest version?

**Comment by thelegendofbrian** [comment]
I used to have a resizing issue similar to this. I played around with it on Win 10 for about 3 minutes and couldn't get it to happen anymore, so it's probably fixed, not sure which commit fixed it though.

**Comment by Hubcapp** [comment]
Works fine for me using AwesomeWM on Debian.

**Comment by OrN** [comment]
Closing this since it appears to be fixed.
