### ISSUE TITLE
Suggestion?

### ISSUE THREAD

**Issue by aldrichdev** [OrN/rscplus#35]
Just dropped this in IRC but I don't think anyone was on.  It would be awesome if you added an optional notification, similar to the "FATIGUED" message, when your inventory is full. Like "INVENTORY IS FULL". 

Thoughts?

**Comment by OrN** [comment]
Sounds good to me. It would be pretty easy to add too

**Comment by aldrichdev** [comment]
Cool! Looking forward to it.

**Comment by thelegendofbrian** [comment]
Is someone working on this yet? If not, I might do it.

**Comment by thelegendofbrian** [comment]
Been a little busy, I'll start on this today.
