### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Fishy666** [OrN/rscplus#41]
First off, love the client and all of the work you people do for it. Thank you so much!

Anyway, would it be possible to add a toggle to keep the different tabs open until you click on a different one? By this I mean, if you click your friends list, it stays open until you open your skills menu, or your inventory, or until you click friends again to close it. I don't know what the limitations are to what you're allowed to add, but I would absolutely love this feature.

**Comment by nickzuber** [comment]
IIRC, doing this is a lot more complicated than you'd expect. I think some guys are looking into it but not sure if its realistically doable. I could be wrong though

**Comment by Hubcapp** [comment]
Yeah, this is labeled "wontfix" b/c it is (or was?) considered cheaty. Should be closed if it's not going to be added.
