### ISSUE TITLE
Feature - Highlight and Block List for Items on the Ground

### ISSUE THREAD

**Issue by nickzuber** [OrN/rscplus#51]
I've recently implemented a highlight and block list for ground items (configurable in the settings). Is this something we'd want to add to the actual client itself? 

If so, I'd be happy to make a proper fork and put up a PR. Let me know!

**Comment by OrN** [comment]
Sounds wonderful!

**Comment by nickzuber** [comment]
Awesome, I'll make a PR soon for this 😄
