### ISSUE TITLE
Graphical Crash on Forceful Screen Focus Request

### ISSUE THREAD

**Issue by tilkinsc** [OrN/rscplus#54]
I was playing league of legends nvidia gtx 1080 sc with latest graphics drivers. League of Legends requests windows focus a lot and it seems quite forceful. It managed to crash the graphics but not page fault or anything. It happened down in edgeville dungeon where I right click to attack a zombie as I clicked league took over. I couldn't tell if I clicked or not. Perhaps this is related to the macOS issue.

**Comment by OrN** [comment]
This may be related to issue https://github.com/OrN/rscplus/issues/4 which is now fixed, can you see if this still happens?

**Comment by tilkinsc** [comment]
Was it updated since 22 days ago?

**Comment by OrN** [comment]
Yes?

**Comment by OrN** [comment]
Closing this for now since it may be a duplicate, if it happens again just reopen the issue.

**Comment by tilkinsc** [comment]
I think it was latest at the time.
