### ISSUE TITLE
generate exe file for distribution

### ISSUE THREAD

**Issue by Hubcapp** [OrN/rscplus#61]
It would be helpful for Windows users if it were possible to generate an exe file. This is in response to recurring messages in the discord server about not knowing what to do with a jar file.

A batch file with the contents "java -jar rscplus.jar" would be a similarly helpful alternative, however "java" is not in the PATH variable by default in windows, so it is not as ideal.

**Comment by OrN** [comment]
Can you look at releases now and the new site and see if that fixes up the rest of this issue report?
