### ISSUE TITLE
Add mouse tooltips

### ISSUE THREAD

**Issue by ShaunDreclin** [OrN/rscplus#81]
Probably a bit late for feature requests but it'd be nice if the "Target: Action" text showed up as a tooltip instead of only being in the top left corner!

Essentially like this (From RuneLite)
![screenshot](https://user-images.githubusercontent.com/5851433/40576219-0abb6196-60c0-11e8-8e34-ec9dc428a142.png)

**Comment by OrN** [comment]
Better now than never, this should be pretty easy to add.

**Comment by nickzuber** [comment]
@OrN @lmsv-mx123 do we have the hooks for this?

**Comment by nickzuber** [comment]
@lmsv-mx123 sweet if you find the hook i don't mind working on the feature

**Comment by lmsv-mx123** [comment]
@nickzuber Hook is placed now at method mouse_action_hook(String tooltipMessage) for Game/Client. Since the position is relative to the top left corner play a bit to determine how a new tooltip comes around using the given message (its in raw format) aka with rsc color codes.

**Comment by nickzuber** [comment]
@lmsv-mx123 awesome work!! I'll start messing around with this soon

**Comment by ShaunDreclin** [comment]
Any progress on this? :D

**Comment by nickzuber** [comment]
I was working on this for a bit and its trickier than we'd expect.

The hook we have tells us what the tooptip in the top left hand corner is when it appears, but doesn't tell us when it _goes away_. I was also having some weird performance issues with having to draw the tooltip each rerender -- but that could just be on my end and fixable.

Not being able to tell when we should remove the tooltip is the biggest blocker right now, @lmsv-mx123 any ideas hook-wise?

**Comment by lmsv-mx123** [comment]
Ok now in the next pull there will be a variable is_hover, which is false when there is no message and true when there is a message because of hover, hopefully that helps out.

**Comment by lmsv-mx123** [comment]
how's the feature coming along @nickzuber ?

**Comment by nickzuber** [comment]
@lmsv-mx123 not much progress since I last worked on it, but I'll play around with it again this weekend. Been super busy recently so I haven't had much time to work on the client

**Comment by OrN** [comment]
https://github.com/OrN/rscplus/tree/mousetext

@nickzuber Here is a start

@lmsv-mx123 your mouse hover doesn't work when right clicking and going over options, and when dialogue options pop up (it still treats the last hovered object as hovered)

I didn't colorize the text, so you can do that too if you want.

**Comment by OrN** [comment]
Fixed with PR https://github.com/OrN/rscplus/pull/132

@ShaunDreclin Can you try the latest client and see if this is good enough? If so, please close the issue :)
