### ISSUE TITLE
Showing username/password after logout

### ISSUE THREAD

**Issue by ShaunDreclin** [OrN/rscplus#9]
It can be handy when switching worlds that my username and password are already filled in, but I don't want that stuff visible when I'm streaming on twitch.

**Comment by thelegendofbrian** [comment]
Would you want it so it didn't save your login info via a config option?

**Comment by ShaunDreclin** [comment]
Yeah that'd be great :o

**Comment by OrN** [comment]
Fixed in the latest version thanks to @thelegendofbrian 

PR https://github.com/OrN/rscplus/pull/10

We could probably handle this better in the future.
